### ISSUE TITLE
Clean UP & Dockerization eos4avb

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/eos4avb#7]

**Comment by HellenNamulinda** [comment]
Hi @GemmaTuron,
While the model files were updated, I checked the actions to know why the build for arm64 failed. I noticed an issue with the versions that had been specified for torch and for rdkit.
at [23945](https://github.com/ersilia-os/eos4avb/actions/runs/5424633068/jobs/9864267301#step:7:23945)
```
#9 505.6 ERROR: Could not find a version that satisfies the requirement torch==1.13.1+cpu (from versions: 1.7.1, 1.8.0, 1.8.1, 1.9.0, 1.10.0, 1.10.1, 1.10.2, 1.11.0, 1.12.0, 1.12.1, 1.13.0, 1.13.1)
#9 505.6 ERROR: No matching distribution found for torch==1.13.1+cpu
```
and at [23923](https://github.com/ersilia-os/eos4avb/actions/runs/5424633068/jobs/9864267301#step:7:23923)
```
#9 505.6 PackagesNotFoundError: The following packages are not available from current channels:
#9 505.6 
#9 505.6   - rdkit=2020.09.1.0
```
Like the previous models I have updated, installing rdkit using conda always fails the arm64 build. I changed this so that rdkit can be installed using pip instead. And for torch, I corrected the version.

Also, I removed the mock.csv.

These changes are reflected in the [PR](https://github.com/ersilia-os/eos4avb/pull/9) I made.

**Comment by GemmaTuron** [comment]
Hi @HellenNamulinda 

The PR appears closed?

**Comment by HellenNamulinda** [comment]
> Hi @HellenNamulinda
> 
> The PR appears closed?

Hi @GemmaTuron,
I had accidentally removed the repo when I was checking for forks.
But I pushed again and re-created the [PR](https://github.com/ersilia-os/eos4avb/pull/10)
